version: "3.3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=danielwq.zhang@mail.utoronto.ca
    volumes_from:
      - nginx-proxy
  frontend:
    env_file:
      - .env
    restart: always
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=ecosquad.me
      - LETSENCRYPT_HOST=ecosquad.me
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
  backend:
    env_file:
      - .env
    restart: always
    image: ghcr.io/uoft-utsc-cs-sandbox/backend-dz365
    container_name: backend
    ports:
      - 3001
    volumes:
      - posts:/usr/src/app/posts
      - avatars:/usr/src/app/avatars
    environment:
      - VIRTUAL_HOST=api.ecosquad.me
      - LETSENCRYPT_HOST=api.ecosquad.me
  postgres:
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      # Different port in case host has Postgres installed already
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # For any persistent storage, you would need to mount a volume to the docker container
    # so that your data stays intact.
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/
  meilisearch:
    image: getmeili/meilisearch:latest
    volumes:
      - meilisearch-data:/data.ms
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_KEY}
      - VIRTUAL_HOST=search.ecosquad.me
      - LETSENCRYPT_HOST=search.ecosquad.me
    ports:
      - "7700:7700"
volumes:
  postgres-volume:
  posts:
  avatars:
  meilisearch-data:
