version: "1.0"
services:
  frontend:
    env_file:
      - .env
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ecosquad-frontend
    ports:
      - 3000:3000
  backend:
    env_file:
      - .env
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ecosquad-backend
    ports:
      - 3001:3001
    volumes:
      - posts:/posts
      - avatars:/avatars
  postgres:
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      # Different port in case host has Postgres installed already
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # For any persistent storage, you would need to mount a volume to the docker container
    # so that your data stays intact.
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./database/:/docker-entrypoint-initdb.d/
volumes:
  postgres-volume:
  posts:
  avatars:
