version: "1.0"
services:
  postgres:
    restart: always
    image: postgres:12
    ports:
      # Different port in case host has Postgres installed already
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # For any persistent storage, you would need to mount a volume to the docker container
    # so that your data stays intact.
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres12/:/docker-entrypoint-initdb.d/
volumes:
  postgres-volume:
